### ISSUE TITLE
Could you please send me a copy of BMS V018 Server Files?

### ISSUE THREAD

**Issue by X-hung** [dilsonnn/wvsapp#3]
It is been a long time when the source code being released, so I am not able to find a copy on the Internet. I am also interested in ms private server development, thus, could you please send me a copy of BMS V018 Server Files? Thanks a lot!

**Comment by dilsonnn** [comment]
They are not available anymore, but you can find here:

https://web.archive.org/web/20150324194926/https://ccplz.net/threads/maplestory-brazil-server-files.478/page-4

**Comment by X-hung** [comment]
> They are not available anymore, but you can find here:
> 
> https://web.archive.org/web/20150324194926/https://ccplz.net/threads/maplestory-brazil-server-files.478/page-4
> http://forum.ragezone.com/f921/official-ms-brazilms-server-files-1038925/
> 
> BTW, you can reverse engineer the tables by using SQL Profiler and IDA for the type structures.

I found it! Thank you so much! I really appreciate it!

**Comment by dilsonnn** [comment]
> > They are not available anymore, but you can find here:
> > https://web.archive.org/web/20150324194926/https://ccplz.net/threads/maplestory-brazil-server-files.478/page-4
> > http://forum.ragezone.com/f921/official-ms-brazilms-server-files-1038925/
> > BTW, you can reverse engineer the tables by using SQL Profiler and IDA for the type structures.
> 
> I found it! Thank you so much! I really appreciate it!

You are welcome!
